---
title: "Análisis IRT - Agosto"
author: "CMEC - PUCP"
date: "23/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)

library(tidyverse)
library(eRm)
library(CTT)
library(DT)
library(rio)

# Modificado para evaluaciones PUCP - Tablas calificación
true.score <- function( dif.items, hab.inf = -6, hab.sup = 6, logit = TRUE) {
    if (!logit) dif.items <- (dif.items-500)/100
    puntaje <- 0
    lista <- NULL
    for(i in seq(hab.inf,hab.sup,0.001)) {
        score <- c(i,sum(exp(i-dif.items)/(1 + exp(i-dif.items))))
        if (puntaje == round( score[2] - 0.5, 0 )) {
            if(is.null(lista)) lista <- score 
            else lista <- rbind(lista,score)
            puntaje <- puntaje + 1
        }
    }
    lista <- data.frame(lista, row.names = paste0("Puntaje ",0:(puntaje-1)))
    names(lista) <- c("Escala", "Puntaje.Aprox")
    lista$Escala <- lista$Escala * 100 + 500
    return(lista)
}

```

```{r}
apc.ciencias <- read.fwf(
  "./DATA_CIENCIAS/ACP_ciencias.txt",
  c(5, 48, 24, 24),
  colClasses = "character",
  col.names = c("code", "mat", "red", "lec")
)

its.ciencias <- read.fwf(
  "./DATA_CIENCIAS/ITS_ciencias.txt",
  c(5, 48, 24, 24),
  colClasses = "character",
  col.names = c("code", "mat", "red", "lec")
)

ibio <- read.fwf(
  "./DATA_CIENCIAS/ITS_ibio.txt",
  c(5, 48, 24, 24),
  colClasses = "character",
  col.names = c("code", "mat", "red", "lec")
)

itsp.ciencias <- read.fwf(
  "./DATA_CIENCIAS/ITS+_ciencias.txt",
  c(5, 48, 24, 24),
  colClasses = "character",
  col.names = c("code", "mat", "red", "lec")
)


apc.letras <- read.fwf(
  "./DATA_LETRAS/ACP_letras.txt",
  c(5, 28, 28, 40),
  colClasses = "character",
  col.names = c("code", "lec", "red", "mat")
)

its.letras <- read.fwf(
  "./DATA_LETRAS/ITS_letras.txt",
  c(5, 28, 28, 40),
  colClasses = "character",
  col.names = c("code", "lec", "red", "mat")
)

arq.letras <- read.fwf(
  "./DATA_LETRAS/ITS_Arqui.txt",
  c(5, 28, 28, 40),
  colClasses = "character",
  col.names = c("code", "lec", "red", "mat")
)

arte.letras <- read.fwf(
  "./DATA_LETRAS/ARTE_ITS.txt",
  c(5, 28, 28, 40),
  colClasses = "character",
  col.names = c("code", "lec", "red", "mat")
)

narte.letras <- read.fwf(
  "./DATA_LETRAS/ARTE_NoITS.txt",
  c(5, 28, 28, 40),
  colClasses = "character",
  col.names = c("code", "lec", "red", "mat")
)

itsp.letras <- read.fwf(
  "./DATA_LETRAS/ITS+_letras.txt",
  c(5, 28, 28, 40),
  colClasses = "character",
  col.names = c("code", "lec", "red", "mat")
)

#ciencias <- bind_rows(apc.ciencias, its.ciencias, ibio, itsp.ciencias)
#letras <- bind_rows(apc.letras, its.letras, arte.letras, narte.letras, arq.letras,itsp.letras)

ciencias <- bind_rows(its.ciencias, ibio)
letras <- bind_rows(its.letras, arq.letras)

```

```{r}
ciencias_mat <-
  data.frame(matrix(
    unlist(strsplit(ciencias$mat, "")),
    nrow = dim(ciencias)[1],
    byrow = TRUE
  ),
  stringsAsFactors = FALSE)
names(ciencias_mat) <- paste0("item-", 1:dim(ciencias_mat)[2])
ciencias_red <-
  data.frame(matrix(
    unlist(strsplit(ciencias$red, "")),
    nrow = dim(ciencias)[1],
    byrow = TRUE
  ),
  stringsAsFactors = FALSE)
names(ciencias_red) <- paste0("item-", 1:dim(ciencias_red)[2])
ciencias_lec <-
  data.frame(matrix(
    unlist(strsplit(ciencias$lec, "")),
    nrow = dim(ciencias)[1],
    byrow = TRUE
  ),
  stringsAsFactors = FALSE)
names(ciencias_lec) <- paste0("item-", 1:dim(ciencias_lec)[2])
```


```{r}
letras_mat <- data.frame(matrix(unlist(strsplit(letras$mat, "")), 
                                      nrow = dim(letras)[1], byrow = TRUE),stringsAsFactors = FALSE)
names(letras_mat) <- paste0("item-",1:dim(letras_mat)[2])
letras_red <- data.frame(matrix(unlist(strsplit(letras$red, "")), 
                                      nrow = dim(letras)[1], byrow = TRUE),stringsAsFactors = FALSE)
names(letras_red) <- paste0("item-",1:dim(letras_red)[2])
letras_lec <- data.frame(matrix(unlist(strsplit(letras$lec, "")), 
                                      nrow = dim(letras)[1], byrow = TRUE),stringsAsFactors = FALSE)
names(letras_lec) <- paste0("item-",1:dim(letras_lec)[2])
```


```{r}
ciencias.mat <- score(ciencias_mat, rep("A", 48), output.scored = TRUE)
ciencias.red <- score(ciencias_red, rep("A", 24), output.scored = TRUE)
ciencias.lec <- score(ciencias_lec, rep("A", 24), output.scored = TRUE)

letras.mat <- score(letras_mat, rep("A", 40), output.scored = TRUE)
letras.red <- score(letras_red, rep("A", 28), output.scored = TRUE)
letras.lec <- score(letras_lec, rep("A", 28), output.scored = TRUE)

```

```{r}
rciencias.mat <- RM(ciencias.mat$scored, se = TRUE, sum0 = TRUE)
rciencias.red <- RM(ciencias.red$scored, se = TRUE, sum0 = TRUE)
rciencias.lec <- RM(ciencias.lec$scored, se = TRUE, sum0 = TRUE)

pciencias.mat <- person.parameter(rciencias.mat)
pciencias.red <- person.parameter(rciencias.red)
pciencias.lec <- person.parameter(rciencias.lec)

fciencias.mat <- itemfit(pciencias.mat)
fciencias.red <- itemfit(pciencias.red)
fciencias.lec <- itemfit(pciencias.lec)

pfciencias.mat <- personfit(pciencias.mat)
pfciencias.red <- personfit(pciencias.red)
pfciencias.lec <- personfit(pciencias.lec)

sepciencias.mat <- SepRel(pciencias.mat)
sepciencias.red <- SepRel(pciencias.red)
sepciencias.lec <- SepRel(pciencias.lec)

```

```{r}
rletras.mat <- RM(letras.mat$scored, se = TRUE, sum0 = TRUE)
rletras.red <- RM(letras.red$scored, se = TRUE, sum0 = TRUE)
rletras.lec <- RM(letras.lec$scored, se = TRUE, sum0 = TRUE)

pletras.mat <- person.parameter(rletras.mat)
pletras.red <- person.parameter(rletras.red)
pletras.lec <- person.parameter(rletras.lec)

fletras.mat <- itemfit(pletras.mat)
fletras.red <- itemfit(pletras.red)
fletras.lec <- itemfit(pletras.lec)

pfletras.mat <- personfit(pletras.mat)
pfletras.red <- personfit(pletras.red)
pfletras.lec <- personfit(pletras.lec)

sepletras.mat <- SepRel(pletras.mat)
sepletras.red <- SepRel(pletras.red)
sepletras.lec <- SepRel(pletras.lec)

```

## Estadísticos por versión

| Grupo    | Evaluados            |
|----------|----------------------|
| Ciencias | `r dim(ciencias)[1]` |
| Letras   | `r dim(letras)[1]`   |

### Indicadores de confiabilidad

| Grupo    | Comprensión de textos             | Redacción (reconocimiento)        | Resolución de problemas           |
|----------|-----------------------------------|-----------------------------------|-----------------------------------|
| Ciencias | `r round(sepciencias.lec[[1]],3)` | `r round(sepciencias.red[[1]],3)` | `r round(sepciencias.mat[[1]],3)` |
| Letras   | `r round(sepletras.lec[[1]],3)`   | `r round(sepletras.red[[1]],3)`   | `r round(sepletras.mat[[1]],3)`   |

```{r}
str.ciencias <- import("./00923 Versión ciencias.xls", sheet = 1, skip = 2, col_names = TRUE)

str.letras <- import("./00923 Versión letras.xls", sheet = 1, skip = 2, col_names = TRUE)

```

```{r}
# Comparar versiones dificultades
indicec_mat <- !is.na(str.ciencias$`Medición`[1:48])
indicec_red <- !is.na(str.ciencias$`Medición`[49:72])
indicec_lec <- !is.na(str.ciencias$`Medición`[73:96])

dstr.ciencias <- str.ciencias$`Medición`
  
dstr.ciencias.mat <- dstr.ciencias[1:48][indicec_mat] - 
  (mean(dstr.ciencias[1:48][indicec_mat]) - mean(-rciencias.mat$betapar[indicec_mat]))
dstr.ciencias.red <- dstr.ciencias[49:72][indicec_red] -
  (mean(dstr.ciencias[49:72][indicec_red]) - mean(-rciencias.red$betapar[indicec_red]))
dstr.ciencias.lec <- dstr.ciencias[73:96][indicec_lec] - 
  (mean(dstr.ciencias[73:96][indicec_lec]) - mean(-rciencias.lec$betapar[indicec_lec]))

indicel_lec <- !is.na(str.letras$`Medición`[1:28])
indicel_red <- !is.na(str.letras$`Medición`[29:56])
indicel_mat <- !is.na(str.letras$`Medición`[57:96])

dstr.letras <- str.letras$`Medición`

dstr.letras.lec <- dstr.letras[1:28][indicel_lec] - (mean(dstr.letras[1:28][indicel_lec]) - mean(-rletras.lec$betapar[indicel_lec]))
dstr.letras.red <- dstr.letras[29:56][indicel_red] - (mean(dstr.letras[29:56][indicel_red]) - mean(-rletras.red$betapar[indicel_red]))
dstr.letras.mat <- dstr.letras[57:96][indicel_mat] - (mean(dstr.letras[57:96][indicel_mat]) - mean(-rletras.mat$betapar[indicel_mat]))

```

```{r}

plot(dstr.ciencias.mat, -rciencias.mat$betapar[indicec_mat], type = "none", cex = 0.7)
text(dstr.ciencias.mat, -rciencias.mat$betapar[indicec_mat], c(1:48)[indicec_mat])
abline(0,1)
abline(-0.5,1, col = "red", lty = "dashed")
abline(0.5,1, col = "red", lty = "dashed")

cmtemp.diff <- c(36,7,38,41,28,12,24,17,34,46) # Se retiran de anclaje

diff.ciencias.mat <- mean(dstr.ciencias.mat[-cmtemp.diff]) - 
  mean(-rciencias.mat$betapar[indicec_mat][-cmtemp.diff])

plot(dstr.ciencias.red, -rciencias.red$betapar[indicec_red], type = "none", cex = 0.7)
text(dstr.ciencias.red, -rciencias.red$betapar[indicec_red], c(1:24)[indicec_red])
abline(0,1)
abline(-0.5,1, col = "red", lty = "dashed")
abline(0.5,1, col = "red", lty = "dashed")

crtemp.diff <- c(23,13,3,19,10,21,17,20,15)

diff.ciencias.red <- mean(dstr.ciencias.red[-crtemp.diff]) - 
  mean(-rciencias.red$betapar[indicec_red][-crtemp.diff])

plot(dstr.ciencias.lec, -rciencias.lec$betapar[indicec_lec], type = "none", cex = 0.7)
text(dstr.ciencias.lec, -rciencias.lec$betapar[indicec_lec], c(1:24)[indicec_lec])
abline(0,1)
abline(-0.5,1, col = "red", lty = "dashed")
abline(0.5,1, col = "red", lty = "dashed")

cltemp.diff <- c(16,14,18,11,3,2)

diff.ciencias.lec <- mean(dstr.ciencias.lec[-cltemp.diff]) - 
  mean(-rciencias.lec$betapar[indicec_lec][-cltemp.diff])

plot(dstr.letras.lec, -rletras.lec$betapar[indicel_lec], type = "none", cex = 0.7)
text(dstr.letras.lec, -rletras.lec$betapar[indicel_lec], c(1:28)[indicel_lec])
abline(0,1)
abline(-0.5,1, col = "red", lty = "dashed")
abline(0.5,1, col = "red", lty = "dashed")

lltemp.diff <- c(28,23,24,13,5,27,26,6,17,18,20)

diff.letras.lec <- mean(dstr.letras.lec[-lltemp.diff]) - 
  mean(-rletras.lec$betapar[indicel_lec][-lltemp.diff])

plot(dstr.letras.red, -rletras.red$betapar[indicel_red], type = "none", cex = 0.7)
text(dstr.letras.red, -rletras.red$betapar[indicel_red], c(1:28)[indicel_red])
abline(0,1)
abline(-0.5,1, col = "red", lty = "dashed")
abline(0.5,1, col = "red", lty = "dashed")

lrtemp.diff <- c(22,20,5,3,8,11,27,15,1,18,6)

diff.letras.red <- mean(dstr.letras.red[-lrtemp.diff]) - 
 mean(-rletras.red$betapar[indicel_red][-lrtemp.diff])

plot(dstr.letras.mat, -rletras.mat$betapar[indicel_mat], type = "none", cex = 0.7)
text(dstr.letras.mat, -rletras.mat$betapar[indicel_mat], c(1:40)[indicel_mat])
abline(0,1)
abline(-0.5,1, col = "red", lty = "dashed")
abline(0.5,1, col = "red", lty = "dashed")

lmtemp.diff <- c(22,4,24,15,9,29)

diff.letras.mat <- mean(dstr.letras.mat[-lmtemp.diff]) - 
  mean(-rletras.mat$betapar[indicel_mat][-lmtemp.diff])

```

```{r}
estructura.ciencias <- data.frame(
  medicion = c(-rciencias.mat$betapar + diff.ciencias.mat + 
    (mean(dstr.ciencias[1:48][indicec_mat][-cmtemp.diff]) - mean(-rciencias.mat$betapar[indicec_mat][-cmtemp.diff])),
               -rciencias.red$betapar + diff.ciencias.red +
            (mean(dstr.ciencias[49:72][indicec_red]) - mean(-rciencias.red$betapar[indicec_red])),
               -rciencias.lec$betapar + diff.ciencias.lec + 
               (mean(dstr.ciencias[73:96][indicec_lec]) - mean(-rciencias.lec$betapar[indicec_lec]))),
  error = c(rciencias.mat$se.beta,
            rciencias.red$se.beta,
            rciencias.lec$se.beta)
  )

estructura.letras <- data.frame(
  medicion = c(-rletras.lec$betapar + diff.letras.lec + 
                 (mean(dstr.letras[1:28][indicel_lec]) - mean(-rletras.lec$betapar[indicel_lec])),
               -rletras.red$betapar + diff.letras.red + 
                 (mean(dstr.letras[29:56][indicel_red][-lrtemp.diff]) - mean(-rletras.red$betapar[indicel_red][-lrtemp.diff])),
               -rletras.mat$betapar + diff.letras.mat + 
                 (mean(dstr.letras[57:96][indicel_mat][-lmtemp.diff]) - mean(-rletras.mat$betapar[indicel_mat][-lmtemp.diff]))),
  error = c(rletras.lec$se.beta,
            rletras.red$se.beta,
            rletras.mat$se.beta)
  )
```

```{r}
file1 <- paste0("Estructura_ciencias_", Sys.Date(),".csv")
file2 <- paste0("Estructura_letras_", Sys.Date(),".csv")

write.csv(estructura.ciencias, file1, row.names = FALSE)
write.csv(estructura.letras, file2, row.names = FALSE)
```

```{r eval=FALSE, include=FALSE}
medicion.ciencias <- data.frame(code = ciencias$code,
   mat = pciencias.mat$theta.table$`Person Parameter` - diff.ciencias.mat + mean(dstr.ciencias[1:48][indicec_mat]),
   red = pciencias.red$theta.table$`Person Parameter` - diff.ciencias.red + mean(dstr.ciencias[49:72][indicec_red]),
   lec = pciencias.lec$theta.table$`Person Parameter` - diff.ciencias.lec + mean(dstr.ciencias[73:96][indicec_lec])
  )

medicion.letras <- data.frame(code = letras$code,
  lec = pletras.lec$theta.table$`Person Parameter` - diff.letras.lec + mean(dstr.letras[1:28][indicel_lec]),
  red = pletras.red$theta.table$`Person Parameter` - diff.letras.red + mean(dstr.letras[29:56][indicel_red]),
  mat = pletras.mat$theta.table$`Person Parameter` - diff.letras.mat + mean(dstr.letras[57:96][indicel_mat])
  )
```
